name: Build and Deploy to GitHub Pages

on:
  workflow_dispatch:
    #nothing, idk

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Build
        run: |
          mkdir -p build
          cd build
          emcmake cmake .. -G Ninja
          cmake --build . --config Release
          cd ..
          cp build/GoldenBase.wasm ./dist
          cp build/GoldenBase.js ./dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4